# Site settings
title: Naevis
email: thenaticswest@gmail.com
description: A D&D 5E setting for OSR games.
domain: world-of-naevis.net
url: https://world-of-naevis.net
theme: just-the-docs

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Exclusions from build
exclude:
  [
    "depreciated/"
  ]

# Note Bars
callouts:
  note:
    title: Note
    color: purple
  background-feature:
    title: Background Feature
    color: purple
  archetypes:
    title: Archetypes
    color: purple
  feat:
    title: Feat
    color: purple
  downtime:
    title: Downtime Activity
    color: purple
  language:
    title: Language
    color: purple
  background-spells:
    title: Background Spells
    color: blue
  mundane-item:
    title: Item
    color: blue
  exotic-language:
    title: Exotic Language
    color: red
  monster:
    title: Monster
    color: purple
